# Generated by Django 4.2.14 on 2024-08-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pup_review', '0003_post_rating_post_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['location_name']},
        ),
        migrations.AddField(
            model_name='post',
            name='review_tagline',
            field=models.CharField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
