# Generated by Django 4.2.14 on 2024-08-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pup_review', '0004_alter_post_options_post_review_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='review_tagline',
        ),
    ]
