# Generated by Django 4.2.14 on 2024-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pup_review', '0005_remove_post_review_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='review_tagline',
            field=models.CharField(default=True, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.IntegerField(choices=[(0, 'Pub'), (1, 'Café'), (2, 'Other')], default=2),
        ),
    ]
