# Generated by Django 4.2.14 on 2024-08-21 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pup_review', '0006_post_review_tagline_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='review_tagline',
        ),
        migrations.AddField(
            model_name='post',
            name='pup_team',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='pup_review_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='location_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
