# Generated by Django 4.2.14 on 2024-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pup_review', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='your_review',
        ),
        migrations.AddField(
            model_name='comment',
            name='my_rating',
            field=models.IntegerField(choices=[(1, '1🐾'), (2, '2🐾'), (3, '3🐾'), (4, '4🐾'), (5, '5🐾')], default=None),
        ),
    ]
