# Generated by Django 4.2.14 on 2024-08-22 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pup_review', '0009_rename_post_comment_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='my_rating',
            new_name='your_rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='pup_review.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews_reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
